### PR TITLE
update readme hunk cycle

### PR DESCRIPTION
**Pull request by derekacosta**
should be Prev so that it actually wraps

### CODE REVIEW

**Comment by airblade** [comment]
The `1` in the previous line takes you to line 1, i.e. wraps the cursor, then you need `GitGutterNextHunk`.

**Comment by derekacosta** [comment]
Maybe its may setup then, but have you tried it yourself?

**Comment by airblade** [comment]
Yes, I tried it at the time and I've just tried it again now.  It's correct as it is.

**Comment by airblade** [comment]
It takes you to next hunk (downwards) in the file.  When you reach the last one, it takes you to the first hunk in the file.

**Pull request closed without merging**
