### PR TITLE
Fix repeat support for GitGutterNextHunk / GitGutterPrevHunk

### PR DESCRIPTION
**Pull request by StarryLeo**

### CODE REVIEW

**Comment by airblade** [comment]
I believe the repeat command `.` is for repeating changes not motions.

**Comment by StarryLeo** [comment]
Ok, forget my stupid understanding. How about do the motions if no do the changes before, Is it possible?

**Comment by airblade** [comment]
What changes before?

**Comment by StarryLeo** [comment]
I mean have not done stage the hunk or undo for current buffer, just want to move between hunks.

**Comment by airblade** [comment]
If you want to keep moving between hunks, do `]c ]c ]c`, or `3]c`.

You can use `.` to repeat the last hunk operation, e.g. staging or undoing.

I often stage a hunk, then move through the other ones in the buffer and stage each one.  The keystrokes are: `gg ]c ghs ]c . ]c .` etc.  (I use `ghs` for staging.)

**Comment by StarryLeo** [comment]
I just want do:
`gg ]c . . . . . . ghs ]c . `
mean: 
`gg ]c ]c ]c ]c ]c ]c ghs ]c ghs`

**Comment by airblade** [comment]
Thanks for the example – I understand what you want.

However vim-repeat only repeats changes

**Comment by StarryLeo** [comment]
This is a wrong demonstration.

**Pull request closed without merging**
