### PR TITLE
Add a call to GitGutterProcessBufferHook, a user-defined hook

### PR DESCRIPTION
**Pull request by jdelkins**
This hook allows for easier integration with other user configuration,
including statuslines, etc.

One specific use case is integration with [lightline](https://github.com/itchyny/lightline.vim), when using information from GitGutterGetHunkSummary in a lightline ```component_expand``` segment.

### CODE REVIEW

**Comment by airblade** [comment]
Thanks for this.

An alternative approach would be for the plugin to fire a user autocommand.  I wonder which is more consistent with the way vim does things?

**Comment by jdelkins** [comment]
Not sure. A user autocmd sounds like a more complete solution, but I was just trying to keep it simple. FWIW [Syntastic takes this approach](https://github.com/scrooloose/syntastic/blob/master/plugin/syntastic.vim#L345) as well. I'd be happy either way!

**Comment by jdelkins** [comment]
I changed to a user autocmd approach with the 2nd commit. I think this is probably better overall. Also added documentation. Feel free to cherry pick whichever approach you prefer. Thanks!

**Comment by airblade** [comment]
Thanks, I prefer the autocmd approach; it feel more decoupled.

Anyway, how about renaming it to just `GitGutter`?

**Comment by jdelkins** [comment]
Done!

**Comment by airblade** [comment]
I was about to merge this when I had a thought: don't we only want to fire the autocmd when `gitgutter#utility#is_active()` is truthy?  I.e. move the autocmd to the last line of that block, just above the `else`?

**Comment by jdelkins** [comment]
I thought it over and I think you are correct.

**Comment by airblade** [comment]
Many thanks!  It's in 27f99c4.

**Pull request closed without merging**
