### PR TITLE
s:on_stderr_nvim: do not call err handler for ['']

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by airblade** [comment]
> With Neovim there is always [''] reported on stderr

Is this a recent change or has Neovim always done that?

**Comment by blueyed** [comment]
Always.

**Comment by blueyed** [comment]
It appears to still work, since the exit handler is called afterwards also.

I've not really investigated, but likely gitgutter sets "path" to -2 first always, but later to the real path (on success).

**Comment by blueyed** [comment]
Yeah, without this patch:

```
setbufvar: 2: path=-1
setbufvar: 2: path=-2
setbufvar: 2: path=src/nvim/tui/input.c
setbufvar: 2: hunks=[]
setbufvar: 2: summary=[0, 0, 0]
setbufvar: 2: hunks=[[13, 0, 14, 1], [362, 1, 363, 2]]
setbufvar: 2: summary=[0, 0, 0]
setbufvar: 2: summary=[1, 0, 0]
setbufvar: 2: summary=[2, 0, 0]
setbufvar: 2: summary=[2, 1, 0]
setbufvar: 2: dummy_sign=0
setbufvar: 2: gitgutter_signs={}
setbufvar: 2: other_signs=[]
setbufvar: 2: dummy_sign=1
setbufvar: 2: dummy_sign=0
setbufvar: 2: tick=3
```

**Comment by airblade** [comment]
Thanks for this.  I think it was working previously by accident ;)

**Comment by blueyed** [comment]
Yes.. :)

**Pull request merged**
