### PR TITLE
plugin/gitgutter.vim: use `command!` to allow for reloading

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by airblade** [comment]
Thanks!

Closed by 2fe748b.

**Comment by blueyed** [comment]
Thanks for merging!
btw: why don't you use GitHub's squash-merge button?

**Comment by airblade** [comment]
I've been going trying different ways of merging patches, just out of curiosity.  Lately I've been using these two scripts (`git-gh-apply` and `git-gh-am`):

```sh
#!/bin/bash

# Applies a patch from a GitHub pull request.
#
# Usage: git gh-apply PULL_REQUEST_URL

curl -LsS "$1.patch" | git apply
```

And:

```sh
#!/bin/bash

# Applies and commits a patch from a GitHub pull request.
#
# Usage: git gh-am PULL_REQUEST_URL

curl -LsS "$1.patch" | git am
```

**Comment by airblade** [comment]
BTW, do you ever reload a plugin?  I always just quit vim and restart.

**Pull request closed without merging**
