### PR TITLE
fix(hunk): summary can't update after preview

### PR DESCRIPTION
**Pull request by kevinhwang91**
I'm not familiar with the code about gitgutter, but it can fix the issue as the title said.

### CODE REVIEW

**Comment by kevinhwang91** [comment]
I don't use vim, it maybe uses `callback` opt for `popup_create`

**Comment by airblade** [comment]
Sorry, I don't understand what problem this fixes.

What is the behaviour you expect to see and what do you actually see?

How can I reproduce the problem?

**Comment by kevinhwang91** [comment]
1. `:GitGutterNextHunk`
2. `:GitGutterPreviewHunk`
3. `:echo GitGutterGetHunkSummary()` outputs `[0 ,0, 0]`
4. close preview hunk, `:echo GitGutterGetHunkSummary()` still outputs `[0 ,0, 0]`

**Comment by airblade** [comment]
The hunk summary is for the whole file.  If you don't stage or undo any hunks, the hunk summary shouldn't change.

What looks weird to me is that the summary is `[0, 0, 0]`, which means there are no changes, and yet you seem to be navigating between hunks.  Does your file actually have any changes or not?

**Comment by kevinhwang91** [comment]
https://asciinema.org/a/391090
Test under Linux with vim 8.2

**Comment by airblade** [comment]
Thanks for the screencast which helped me understand the problem.

Thanks too for the patch.  However I think it fixes the symptoms rather than the actual cause, which I believe 6019d43 fixes.

**Comment by kevinhwang91** [comment]
nice:)

**Pull request closed without merging**
