### PR TITLE
Add BOM support.

### PR DESCRIPTION
**Pull request by nagaohiroki**
<feff> is invisible from github...

### CODE REVIEW

**Comment by airblade** [comment]
Thanks!

The docs for `'bomb'` say:

> 	When writing a file and the following conditions are met, a BOM (Byte
>	Order Mark) is prepended to the file:
>	- this option is on
>	- the 'binary' option is off
>	- 'fileencoding' is "utf-8", "ucs-2", "ucs-4" or one of the little/big
>	  endian variants.

Your patch tests the first condition; shouldn't we also test the other two conditions?

**Comment by airblade** [comment]
Writing the buffer used to be implemented with `:write` but I changed it to use `writefile()` in 4e911819be.  `:write` was ok but had several side-effects which had to be dealt with, which was annoying.  I don't plan to revert to `:write`.

**Comment by airblade** [comment]
I think all we need do is add a check to see whether `fileencoding` is one of the ones listed in the `bomb` help doc.

**Comment by airblade** [comment]
Hmm, actually I think your original patch is fine :)  If `bomb` is set, then we should write it back out.

**Comment by airblade** [comment]
I merged your original commit (3724e1c).  Thanks again!

**Comment by nagaohiroki** [comment]
thank you very much!
my english is slow(sorry)

**Comment by airblade** [comment]
Your English is better than my Japanese :)

**Pull request closed without merging**
